### ISSUE TITLE
Sort by company and personal

### ISSUE THREAD

**Issue by forteller** [transitive-bullshit/awesome-oss-funding#2]
Thanks for making this!

Just wanted to add: I think it would be very helpful if there where two lists, one for companies (and larger entities, like organizations, cities, municipalities, etc) and one for individuals.

If I as an individual want to fund some Free software, I don't need to see opportunities that are really only usable by larger entities. 

For example, if I as an individual want to donate I can do that trough Liberapay, but not trough Tidelift. Maybe then they should be on different lists?

Just a thought. Thanks again!

**Comment by transitive-bullshit** [comment]
Definitely a useful piece of feedback.

We're a bit constrained by the format of the [Awesome Lists project](https://github.com/sindresorhus/awesome#readme) but if other people agree and/or you want to suggest a way to better clarify this distinction on the list, I'd be happy to consider your suggestions. 😄 

Also, maybe [oss.fund](http://oss.fund/) will be more useful in these cases since it allows you to filter by different characteristics?

Thanks!!
